### ISSUE TITLE
Buying a POS with more than 4 rows is impossible

### ISSUE THREAD

**Issue by km127pl** [cloudnode-pro/BankAccounts#37] opened 2023-08-25 19:58 UTC
You physically cannot buy a POS that has more rows than the player's inventory as it'll not fit.

**Comment by zefir-git** [comment] 2023-08-27 15:51
Isn't this duplicate of #35

**Comment by km127pl** [comment] 2023-08-28 00:02
It is, but a different part of the POS

**Closed** 2023-11-08 20:32 UTC
Labels: bug
